fil = ["BTC",
"Digitel",
"Azercell",
"Bouygues Telecom",
"MegaFon",
"Three Hutchinson",
"Three Hutchinson",
"WIND HELLAS",
"NTT DoCoMo",
"Hong Kong Telecom",
"MAROC Telecoms",
"Jersey Telecom",
"Three Hutchinson",
"Three Hutchinson",
"Three Hutchinson",
"Wind Hitchinson(formelrly Veon)",
"TeliaSonera",
"Three Hutchinson",
"Millicom Group(TIGO)",
"Millicom Group(TIGO)",
"Millicom Group(TIGO)",
"Millicom Group(TIGO)",
"Millicom Group(TIGO)",
"Orange Dominicana(Now Altice",
"Nova Iceland",
"Optus Mobility Ltd",
"A1 Telecom Group",
"A1 Telecom Group",
"A1 Telecom Group",
"A1 Telecom Group",
"Sure (Guernsey) Limited",
"Hutchinson",
"Reliant Jio",
"Telkomsel Indonesia",
"TIM Italy",
"A1 Telecom Group",
"CTM",
"Hutchinson",
"A1 Telecom Group",
"Globe Philippines",
"Smart",
"A1 Telecom Group",
"A1 Telecom Group",
"LG Plus",
"SK Telecom",
"Sunrise",
"Chunghwa Telecom",
"Antel",
"Indigo Wireless",
"Telefonica Latam Group",
"WOM Chile",
"Everything Everywhere",
"jersey Airtel Ltd",
"Turkcell",
"Vodafone",
"SKY Telecom",
"AMX Group",
"Telstra Corp Ltd",
"Orange Group",
"Proximus Group",
"AMX Group",
"TIM Brazil",
"AMX Group",
"AMX Group",
"AMX Group",
"I.C.E. Costa Rica",
"Cubacell",
"AMX Group",
"AMX Group",
"Telenor Group",
"Free Mobile",
"Orange Group",
"AMX Group",
"AMX Group",
"Bharti Airtel",
"Softbank Mobile Corp",
"Safaricom",
"Orange Group",
"Proximus Group",
"Orange Group",
"AMX Group",
"AMX Group",
"Etisalat",
"AMX Group",
"AMX Group",
"Orange Group",
"AMX Group",
"Orange Group",
"Singtel Telecoms",
"Starhub",
"Orange Group",
"Orange Group",
"Dialog Axiata",
"Salt",
"Swisscom Switzerland",
"AIS Thailand",
"AMX Group",
"Three Hutchinson",
"Polkomtel (Plus)",
"Eastlink Canada",
"Veon Group",
"Veon Group",
"Entel Bolivia",
"Tele2 Group",
"Tele2 Group",
"Veon Group",
"Jersey Telecom",
"Tele2 Group",
"VEON Group",
"VEON Group",
"Tele2 Group",
"Tele2 Group",
"Tele2 Group",
"VEON Group",
"Tele2 Group",
"VEON Group",
"ELISA",
"VEON Group",
"VEON Group",
"Telecom Personal",
"TeliaSonera",
"TeliaSonera",
"TeliaSonera",
"TeliaSonera",
"TeliaSonera",
"Telenor Group",
"TeliaSonera",
"Three Hutchinson",
"AMX Group",
"Be Aliv (NewCo)",
"Telenor Group",
"Belize Telemedia",
"AMX Group",
"Telenor Group",
"AMX Group",
"Entel Chile",
"AMX Group",
"AMX Group",
"Telefonica Europe Group",
"Tele2 Group",
"AMX Group",
"AMX Group",
"Digicel South Pacific Ltd",
"Altice (SFR) Group",
"AMX Group",
"AMX Group",
"Telenor Group",
"Altice Group",
"Telenor Group",
"AMX Group",
"Telenor Group",
"Telenor Group",
"KPN Group",
"AMX Group",
"TeliaSonera",
"Telenor Group",
"Digicel South Pacific Ltd",
"AMX Group",
"AMX Group",
"Altice Group",
"AMX Group",
"Altice Group",
"Telenor Group",
"Telefonica Europe Group",
"Telcell St. Maarten",
"Telenor Group",
"Telenor Group",
"Digicel South Pacific Ltd",
"AMX Group",
"Digicel South Pacific Ltd",
"Digicel South Pacific Ltd",
"UTS",
"UTS",
"UTS",
"Pelephone Communications",
"Millicom Group(TIGO)",
"Videotron",
"Millicom Group(TIGO)",
"Deutsche Telekom Group",
"Partner Communications",
"Millicom Group(TIGO)",
"Alaska Wireles",
"Vodafone Group",
"Vodafone Group",
"Deutsche Telekom Group",
"Deutsche Telekom Group",
"Deutsche Telekom Group",
"Vodafone Group",
"Vodafone Group",
"Deutsche Telekom Group",
"Vodafone Group",
"Vodafone Group",
"Deutsche Telekom Group",
"Vodafone Group",
"Millicom Group(TIGO)",
"Millicom Group(TIGO)",
"Deutsche Telekom Group",
"Vodafone Group",
"Vodafone Group",
"Vodafone Group",
"Deutsche Telekom Group",
"Vodafone Group",
"Deutsche Telekom Group",
"Vodafone Group",
"Vodafone Group",
"Deutsche Telekom Group",
"Deutsche Telekom Group",
"Vodafone Group",
"Deutsche Telekom Group",
"Vodafone Group",
"Deutsche Telekom Group",
"Vodafone Group",
"Vodafone Group",
"Vodafone Group",
"Vodafone Group",
"AT&T",
"AT&T Mobility",
"Bell Mobility",
"Sasktel",
"Telus",
"China Mobile",
"China Mobile Hong Kong",
"Verizon Wireless",
"Telefonica Latam Group",
"Telefonica Latam Group",
"Freedom Mobile (Formerly Wind Mobile)",
"Telefonica Latam Group",
"Telefonica Latam Group",
"Telefonica Latam Group",
"Telefonica Latam Group",
"Telefonica Europe Group",
"Telefonica Latam Group",
"Deutsche Telekom Group",
"Deutsche Telekom Group",
"Telefonica Latam Group",
"Telefonica Latam Group",
"Telefonica Latam Group",
"Telefonica Europe Group",
"Telefonica Europe Group",
"Telefonica Latam Group",
"Rogers",
"Sprint",
"T-MOBILE",
"Free Mobile",
"Altice (SFR) Group",
"Bouygues Telecom",
"Altice (SFR) Group",
"Altice (SFR) Group",
"TIM Celular S.A.",
"KDDI",
"KDDI",
"Siminn",
"UkrainianRadio(Martime) -Ukraine",
"Afghan Telecom",
"Afghan Wireless",
"Etisalat",
"TDCA (Roshan)",
"Movicel",
"Eagle Mobile",
"TelCell N.V.",
"du",
"Etisalat",
"Thuraya - Dubai",
"Vivacel",
"Orange",
"Karabakh Telecom - Armenia",
"Bluesky",
"Orange",
"H3G",
"Azerfon",
"Backcell",
"Libercom - Benin",
"Airtel",
"Telcel",
"Axiata Bangladesh Ltd",
"Warid (Airtel)",
"Vivacom",
"Batelco",
"Viva",
"BTC",
"M:tel",
"CJSC 'Best' (Belarusian Telecommunication)",
"Mobile TeleSystems JLLC (MTS)",
"Entel S.A.",
"TIGO Telecel",
"Oii",
"Oii",
"DST",
"B Mobile - Brunei",
"BTC",
"Orange",
"Telecel",
"Atlantique",
"Nextel",
"ENTEL PCS Telecomunicaciones S.A",
"Claro",
"Atlantique Telecom",
"Sim Ivoiris - Cote D'Ivoires - IVORY COAST",
"Comium",
"Green Network - CÔTE D’IVOIRE",
"Celtel Congo RDC Congo",
"Africell RDC sprl",
"Sait Tekecom (Oasis)",
"Airtel",
"Warid",
"Telecom",
"Colombia Movil (TIGO)",
"T+Telecomunicacoes - Cape Verde",
"Telefonica",
"C Com (Cubacel)",
"MTN",
"E-Plus",
"Telia",
"Hi3G",
"Trilogy",
"Alegro",
"Etisalat",
"Mobinil (Orange)",
"Vodafone",
"Orange",
"EMT",
"Elisa",
"Ethio Telecom",
"Elisa",
"DNA",
"DNA",
"Elisa",
"TeliaSonera",
"SFR",
"SFR",
"Free Mobile",
"Tikiphone",
"Faroese Telecom",
"Airtel",
"Atlantique Telecom",
"Cable & Wireless",
"Orange (EE)",
"Sure (Cable & Wireless)",
"Hutchison 3G",
"T-Mobile (GBRME)",
"Sure (Cable & Wireless)",
"MagtiCom GSM",
"Tigo",
"SPACEFON",
"Airtel",
"CTS",
"GibtelCom",
"Intercel",
"Gamcel",
"Q'Cell",
"Orange - Equatorial Guinea",
"GREEN COM S.A (HITS)",
"Wind Hellas - Greece",
"Wind",
"Comunicaciones Celulares- S.A., Guatemala",
"Telefonica Moviles",
"Docomo Pacific",
"Docomo Pacific",
"Webbing Hong Kong Limited",
"Telefonica",
"Sercom",
"Sercom",
"ComCEL",
"Hutchison 3G",
"Excelcomindo",
"AXIS",
"Telkomsel",
"Dishnet Wireless Jammu",
"Dishnet Wireless Himachal",
"Dishnet Wireless West Ben",
"Dishnet Wireless Bihar",
"Dishnet Wireless Orissa",
"Dishnet Wireless Assam",
"Dishnet Wireless North",
"Dishnet Wireless Kolkata",
"Dishnet Wireless UP East",
"Dishnet Wireless UP West",
"Aircel Limited Dehli",
"Dishnet Wireless Kerala",
"Aircel Limited Mumbai",
"Aircel Limited Karnataka",
"Aircel Limited Andhra Pradesh",
"Aircel Limited Maharashtra/Goa",
"Dishnet Wireless Punjab",
"Aircel Limited Rajasthan",
"Dishnet Wireless Madhya",
"Aircel Limited Gujarat",
"Dishnet Wireless Harya",
"AIRCEL LTD. India",
"Loop Mobile",
"Vodafone (Kerala)",
"Vodafone (Maharashtra & Goa)",
"IDEA (Maharashtra & Goa)",
"Vodafone (Tamil Nadu)",
"Vodafone (Kolkata)",
"MTNL(Delhi) -India",
"Vodafone (Delhi)",
"Vodafone (Gujarat)",
"Vodafone (Mumbai)",
"IDEA (Kolkata - INDIK)",
"MTNL(Mumbai) - India",
"AIRCEL LIMITED",
"Reliance",
"Tata TeleServices AP",
"Tata TeleServices Karnataka",
"Tata TeleServices Tamil Nadu",
"Tata TeleServices Kerala",
"Tata TeleServices HP",
"Tata TeleServices MP",
"Tata TeleServices Maharashtra",
"Tata TeleServices UP East",
"Tata TeleServices UP West",
"Tata TeleServices RO WB",
"Tata TeleServices Bihar",
"Tata TeleServices Delhi",
"Tata TeleServices Gujarat",
"Tata TeleServices Haryana",
"Tata TeleServices Kolkata",
"Tata TeleServices Mumbai",
"Tata TeleServices Orissa",
"Tata TeleServices Punjab",
"Tata TeleServices Rajasthan",
"BSNL",
"O2 Communications",
"Hutchison 3G",
"MTN Irancell",
"RighTel",
"Asiacell Iraq",
"KorekTel",
"Nova",
"Siminn",
"Siminn",
"Vodafone",
"Viking Wireless (IMC)",
"Cellcom - Israel",
"Fastlink",
"Umniah - Jordan",
"ALTEL JSC",
"YU Telecom - Kenya",
"Telekom (Orange)",
"Beeline - Kyrgyzstan",
"Nurtelecom",
"CAM GSM Cambodia",
"Cadcomms",
"Latelz",
"Applifone Company - Cambodia",
"CAM GSM Cambodia",
"ATHKL Kiribati",
"KTF - South Korea",
"Viva",
"Ooredoo (Wataniya)",
"Lao Telecommunications",
"MIC",
"Mobile Interim Company number",
"Cellcom",
"Almadar",
"Orange",
"Etisalat",
"Dialog",
"Hutchison",
"Mobitel - Sri Lanka",
"Econet",
"Vodacom",
"Orange (Vox Mobile)",
"Tango",
"Smartone Macao",
"Meditel Orange Morocco",
"WANA",
"Monaco Telecom",
"ORANGE MOLDOVA",
"Airtel",
"Telma",
"Dhiraagu",
"Wataniya Telecom - Maldives",
"T-Mobile",
"Orange",
"Go Mobile",
"Melita Mobile",
"Myanmar Posts and Telecommunications",
"Ooredoo",
"Mtel",
"Unitel LLC - MONGOLIAN PEOPLE'S REP.",
"Mobicom",
"MCel - Mozambique",
"Mattel",
"Emtel",
"Orange",
"MTL",
"Airtel",
"Telekom Network Malawi (TNM) Ltd.",
"Maxis",
"U Mobile (Mi3G Network Sdn Bhd)",
"Leo",
"OPT",
"Orange",
"Etisalat",
"Glo Mobile",
"Network Norway",
"Ncell",
"Omantel",
"Nawras",
"Pak Telecom Mobile",
"Nextel",
"Claro",
"Palau Mobile Corporation - Palau",
"Palau Mobile Corporation",
"Centertel (Orange)",
"P4 (Play)",
"Claro",
"TMN",
"Nucleo",
"Tigo",
"Jawwal (Palestine Cellular Comm)",
"Wataniya",
"Q-Tel (Ooredoo)",
"Orange",
"Orange",
"MTS",
"NTC",
"T2 Mobile LCC",
"LLC",
"T2 Mobile LCC",
"Airtel",
"Tigo",
"STC",
"Etisalat Mobily - Saudi Arabia",
"Zain (MTC)",
"Sudan Telecom",
"Expresso",
"Sonatel",
"Tigo (Sentel)",
"Mobile One (M1)",
"Solomon Telekom",
"TIGO (Millicom)",
"Telemovil El Salvador",
"San MarinoTelecom",
"CST, Companhia Santomense de Telecomunicacoes",
"Zain (MTC)",
"Orange",
"Mobiltel",
"Tusmobil",
"T-2 Slovenia",
"Hi3G",
"Cable & Wireless",
"Airtel",
"MIC Tchad (Millicom)",
"UAT TEST2",
"Togo Cellelaire",
"Moov",
"Real Future (TrueMove)",
"TrueMove",
"Real Future (TrueMove)",
"Babilon",
"Tcell",
"Tcell",
"BCTI - Turkmenistan",
"TMCELL",
"Timor Telecom",
"Orange",
"Tunisie Telecom",
"AVEA - Turkey",
"Avea",
"Far East Tone",
"Taiwan Mobile Co. Ltd.",
"MIC/Mobitel",
"Vodacom",
"Orange (Africell)",
"Uganda Telecom",
"WaridTel",
"Ukraine Radio - Ukraine",
"Golden Telecom",
"Astelit",
"Antel",
"Airadigm - USA",
"Limitless Mobile LLC USA",
"Limitless Mobile USA",
"Pulse Mobile",
"DCH MACH PRIVATE RAP",
"Ucell",
"Uzdunrobita - Uzbekistan",
"Vinaphone",
"Mobifone",
"Viettel Mobile",
"Vietnamobile (Hanoi Telecom Joint Stock Company)",
"Telecom Vanuatu Limited",
"Orange (Manuia)",
"Bluesky",
"TELEKOM SRBIJA, SERBIA",
"Cell C",
"MTN",
"Airtel",
"FSM",
"Videotron",
"Kcell",
"Hutchison 3G",
"Truphone",
"KPN Telfort Netherlands",
"KPN Netherlands",
"Pacific Mobile Telecom",
"Tele2",
"Tele2",
"Tele2",
"Tele2",
"Tele2 - Sweden",
"Telefonica Moviles",
"Vivo",
"Vivo",
"Vivo",
"Vivo",
"Telefonica Moviles (Movistar)",
"Telefonica Moviles",
"Telefonica Moviles/Pegaso",
"Telefonica (Celular de Nicarragua)",
"Movistar (Telefonica)",
"Telefonica Moviles",
"Telefonica Moviles/Abiator",
"Viaero Wireless, USA",
"O2 Communications",
"Telefonica",
"Telefonica 02",
"Telefonica",
"Telefonica Moviles",
"O2 Communications",
"Globe Telecom",
"Bouygues Telecom",
"Entel Telefonica Movil",
"Mobilkom",
"Orange - Austria",
"Mobilkom",
"Mobitel - Bulgaria",
"Velcom",
"Vipnet",
"eAccess",
"KT",
"One.Vip DOO Skopje - Macedonia",
"VIP Mobile",
"VIP Mobile",
"Si Mobil",
"Vodafone",
"Wind",
"Indosat",
"Indosat",
"Sure (Cable & Wireless)",
"Polkomtel",
"Tele",
"Two Degrees (NZ Communications)",
"ArmenTel (Beeline)",
"Banglalink",
"Kar-Tel (Beeline)",
"Lao Telecommunications",
"Mobilink",
"Warid",
"Beeline",
"Kyivstar",
"Unitel - Beeline",
"Hutchison 3G",
"Hutchison-2G",
"Hutchison",
"Tele2 Russia",
"Digicel - Aruba",
"Digicel",
"Digicel",
"Digicel",
"Digicel",
"Starhub",
"Digicel",
"Digicel",
"Telecom North America",
"SmarTone/Vodafone",
"Digicel",
"Digicel",
"Digicel",
"NTT Docomo",
"Transatel - France",
"Telenor",
"Telenor (formerly Pannon)",
"Digi",
"Telenor",
"Telenor",
"Trinet (Dtac)",
"DTAC",
"SingTel - Singapore",
"SingTel",
"Sunrise",
"AT&T (Maritime Services)",
"AT T Comercializacion Movil",
"Communicaciones Nextel",
"AT&T",
"AT&T - USA",
"AT&T",
"AT&T",
"ATT-USA",
"AT&T",
"AT&T - USA",
"China Unicom",
"China Unicom",
"China Mobile/Peoples",
"HKT (PCCW)-3G",
"HKT (PCCW)-2G",
"CSL - HK",
"CSL/New World Mobility",
"Sprint Nextel",
"Sprint Nextel",
"Sprint Nextel",
"Belgacom(Proximus)",
"Bell Mobility",
"SaskTel",
"Telus",
"China Telecommunications Corporation",
"Bharti Airtel - UP East",
"Bharti Airtel - Orissa",
"Bharti Airtel - Bihar",
"Bharti Airtel - Jammu & Kashmir",
"Bharti Airtel - West Bengal",
"Bharti Airtel - Assam",
"Bharti Airtel - North East",
"Bharti Airtel - Mumbai",
"Bharti Airtel - Maharashtra",
"Bharti Airtel - Gujarat",
"Bharti Airtel - Tamil Nadu",
"Bharti Airtel - Haryana",
"Bharti Airtel - Uttar Pradesh West",
"Bharti Airtel - Kerala",
"Bharti Airtel - Madhya Pradesh",
"Bharti Airtel - Punjab",
"Bharti Airtel - Delhi",
"Bharti Airtel - Himachal Pradesh",
"Bharti Airtel - Rajasthan",
"Bharti Airtel - Karnataka",
"Bharti Airtel - Andhra Pradesh",
"Bharti Airtel - Kolkata",
"Bharti Airtel - Chenai",
"Pelephone - Israel",
"SoftBank",
"LGU+",
"Cosmote - Romania",
"T Mobile - USA",
"TMobile - USA",
"Fido",
"Rogers Wireless",
"China Mobile",
"China Mobile",
"China Mobile",
"Taiwan Mobile",
"Celcom",
"Celcom - Malaysia",
"CTM",
"Orange",
"Meteor",
"Digitel",
"Smart",
"MegaFon",
"Verizon",
"Verizon",
"Swisscom",
"Vodafone",
"Orange",
"AIS",
"AWN (AIS)",
"Chungwa",
"Startel (Vibo)",
"Optus",
"T-Mobile",
"T-Mobile",
"KPN Grp (Base) - Belgium",
"T-Mobile",
"Telekom Deutschland GmbH (T-Mobile)",
"Cosmote",
"T-Mobile",
"Telecom (TIM)",
"SK Telecom",
"Bite",
"P&T (Lux GSM)",
"Bite",
"T-Mobile",
"T-Mobile",
"Digicel",
"T-Mobile (Era)",
"T-Mobile (Slovac Telecom)",
"Digicel",
"T-Mobile - USA",
"T-Mobile USA",
"T-Mobile - USA",
"T-Mobile USA",
"T-Mobile USA",
"T-Mobile USA",
"T-Mobile USA",
"T-Mobile",
"T-Mobile",
"Digicel",
"Digicel",
"Telecom New Zealand",
"Vodafone Malta Ltd - Terrestrial",
"Vodafone",
"VODACOM CONGO",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodacom",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodafone",
"Vodacom",
"Telstra",
]

store = []
for x in fil:
    if not x in store:
        store.append(x)

f = open("files/final.csv", "a")
for x in store:
    f.write("{" + x + "}")
f.close()
